config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :users do
    resources :avatars
  end
  get 'users/:id' => 'users#show'
  resources :ideas

  get 'welcome/index'
  resources :teachers

  root 'welcome#index'
end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  validates :picture, presence: true
  
  mount_uploader :picture, AvatarUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_avatar
  
  def crop_avatar
    picture.recreate_versions! if crop_x.present?
  end
end

app/models/idea.rb
class Idea < ActiveRecord::Base
    mount_uploader :picture, PictureUploader
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
    validates :username,  presence: true, length: { maximum: 20 }, uniqueness: true
    validates :password,  presence: true, confirmation: true, if: lambda{ new_record? || !password.nil? }
    validates :email_address, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :avatars
  validates :username,  presence: true, length: { maximum: 20 }, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @avatars = Avatar.all
  end
  
  def show
    @user = User.find(params[:user_id])
    @avatar = @user.avatars.find(params[:id])
  end
  
  def new
    @user = User.find(params[:user_id])
    @avatar = Avatar.new
  end

  def create
    @user = User.find(params[:user_id])
    @avatar = @user.avatars.create(avatar_params)
    if @avatar.save
      if params[:avatar][:picture].present?
        render :crop
      else
        redirect_to action: 'index'
      end
    else
      render :new
    end
  end
  
  def edit
     @user = User.find(params[:user_id])
     @avatar = @user.avatars.find(params[:id])
  end
  
  def update
    @user = User.find(params[:user_id])
    @avatar = @user.avatars.find(params[:id])
    if @avatar.update(avatar_params)
      if params[:avatar][:picture].present?
        render :crop
      else
        redirect_to action: 'index'
      end
    else
      render :edit
    end
  end
  
  def destroy
    @avatar = Avatar.find(params[:id])
    @avatar.destroy
     
    redirect_to action: 'index'
  end
    
  private
    def avatar_params
      params.require(:avatar).permit(:title, :description, :picture, :crop_x, :crop_y, :crop_w, :crop_h)
    end
  
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    def new
        @teacher = Teacher.new
    end
    
    def index
      @teachers = Teacher.all
    end
    
    def create
      @teacher = Teacher.new(teacher_params)
     
      if @teacher.save
        redirect_to @teacher
      else
        render 'new'
      end
    end
    
    def show
      @teacher = Teacher.find(params[:id])
    end
    
    def edit
      @teacher = Teacher.find(params[:id])
    end
    
    def update
      @teacher = Teacher.find(params[:id])
     
      if @teacher.update(teacher_params)
        redirect_to @teacher
      else
        render 'edit'
      end
    end
    
    def destroy
      @teacher = Teacher.find(params[:id])
      @teacher.destroy
     
      redirect_to teachers_path
    end
    
    private
      def teacher_params
        params.require(:teacher).permit(:username, :password, :password_confirmation,:name, :email_address, :date_of_birth)
      end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 
  private
 
  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
 
  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
      @user = User.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/avatars/_form.html.erb
<%= form_for([@user, @avatar]) do |f| %>
  <% if @avatar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@avatar.errors.count, "error") %> prohibited this avatar from being saved:</h2>

      <ul>
      <% @avatar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/avatars/crop.html.erb
<% content_for :javascript do %>
  <%= stylesheet_link_tag 'jquery.Jcrop' %>
  <%= javascript_include_tag 'jquery.Jcrop' %>
<% end %>

<h1>Crop Avatar</h1>

<%= image_tag @avatar.picture_url(:large), id: "cropbox" %>

<h4>Preview</h4>
<div style="width:100px; height:100px; overflow:hidden">
  <%= image_tag @avatar.picture_url(:large), :id => "preview" %>
</div>

<%= form_for [@user, @avatar] do |f| %>
  <% %w[x y w h].each do |attribute| %>
    <%= f.hidden_field "crop_#{attribute}" %>
  <% end %>
  <div class="actions">
    <%= f.submit "Crop" %>
  </div>
<% end %>

app/views/avatars/edit.html.erb
<h1>Editing Avatar</h1>

<%= render 'form' %>

<%= link_to 'Back', user_avatar_path(@user,@avatar) %>

app/views/avatars/index.html.erb
<h2><strong><%= @user.email %></strong> Avatars</h2>
<% @user.avatars.each do |avatar| %>
  <p>
    <strong>Title:</strong>
    <%= avatar.title %>
  </p>
 
  <p>
    <strong>Description:</strong>
    <%= avatar.description %>
  </p>
  
  <p>
    <strong>Picture:</strong>
    <%= image_tag avatar.picture_url(:avatar) if avatar.picture? %>
    <%= link_to 'show', user_avatar_path(avatar.user,avatar) %>
    |<%= link_to 'Edit', edit_user_avatar_path(avatar.user,avatar) %>
    |<%= link_to 'Destroy Avatar', [avatar.user, avatar],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

<%= link_to 'Add Avatar', new_user_avatar_path(@user), class:"btn btn-primary" %>

app/views/avatars/new.html.erb
<h1>New Avatar</h1>

<%= render 'form' %>

<%= link_to 'Back', user_avatars_path(@user) %>

app/views/avatars/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @avatar.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @avatar.description %>
</p>
<p>
  <%= image_tag @avatar.picture_url(:large) if @avatar.picture? %>
</p>
<p>

<%= link_to 'Edit', edit_user_avatar_path(@user,@avatar) %> |
<%= link_to 'Back', user_avatars_path(@user) %>

app/views/ideas/_form.html.erb
<%= form_for @idea, :html => {:multipart => true} do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= image_tag idea.picture_url(:thumb) if idea.picture? %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@idea.picture_url, :width => 600) if @idea.picture.present? %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Site</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :javascript %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">The Idea app</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if params[:controller] == 'ideas' %>"><%= link_to "Ideas", ideas_path %></li>
            <li class="<%= 'active' if params[:controller] == 'teachers' %>"><%= link_to "Teachers", teachers_path %></li>
          </ul>
          
          <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>
      </div>
    </nav>
    
    <div class="container">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <%= yield %>
    </div>
    
    <footer>
      <div class="container">
        Rails Girls 2014
      </div>
    </footer>
</body>
</html>

app/views/teachers/_form.html.erb
<%= form_for @teacher do |f| %>
<form role="form">
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited
        this teacher from being saved:</h2>
        <ul>
        <% @teacher.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
  <% end %>
  <div class="form-group">
    <label for="username"><%= f.label :username %></label>
    <%= f.text_field :username, :class => "form-control", :placeholder => "Username" %>
  </div>
  <% if @teacher.new_record? %>
      <div class="form-group">
        <label for="password"><%= f.label :password %></label>
        <%= f.password_field :password, :class => "form-control", :placeholder => "Password" %>
      </div>
      <div class="form-group">
        <label for="password_confirmation"><%= f.label :password_confirmation %></label>
        <%= f.password_field :password_confirmation, :class => "form-control", :placeholder => "Password" %>
      </div>
  <% end %>
  <div class="form-group">
    <label for="name"><%= f.label :name %></label>
    <%= f.text_field :name, :class => "form-control", :placeholder => "name" %>
  </div>
  <div class="form-group">
    <label for="email_address"><%= f.label :email_address %></label>
    <%= f.email_field :email_address, :class => "form-control", :placeholder => "Email Address" %>
  </div>
  <div class="row">
      <div class="form-group col-md-3 col-sm-3">
        <label for="date_of_birth"><%= f.label :date_of_birth %></label>
        <%= f.date_field :date_of_birth, :class => "form-control", :placeholder => "Date Of Birth" %>
      </div>
  </div>
  <%= f.submit "submit", :class => "btn btn-default" %>
</form>
<% end %>

app/views/teachers/edit.html.erb
<h2>Edit <%= link_to @teacher.name, teacher_path(@teacher), class: "" %></h2>
 
<%= render 'form' %>
 

app/views/teachers/index.html.erb
<h2>Listing teachers</h2>
 
<%= link_to 'New Teacher', new_teacher_path, class:"btn btn-danger" %>
<br /><br />
  
<table class="table table-bordered">
  <tr>
    <th>Username</th>
    <th>Name</th>
    <th>Email Address</th>
    <th>Date Of Birth</th>
    <th></th>
  </tr>
 
  <% @teachers.each do |teacher| %>
    <tr>
      <td><%= teacher.username %></td>
      <td><%= teacher.name %></td>
      <td><%= teacher.email_address %></td>
      <td><%= teacher.date_of_birth %></td>
      <td>
        <div class="btn-group btn-group-sm">
          <%= link_to 'Show', teacher_path(teacher), class: 'btn btn-primary' %>
          <%= link_to 'Edit', edit_teacher_path(teacher), class: 'btn btn-primary' %>
          <%= link_to 'Destroy', teacher_path(teacher), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %>
        </div>
     </td>
    </tr>
  <% end %>
</table>

app/views/teachers/new.html.erb
<h2>New Teacher</h2>

<%= render 'form' %>

app/views/teachers/show.html.erb
<table class="table table-hover">
  <tr>
    <th>Username</th>
    <td><%= @teacher.username %></td>
  </tr>
  <tr>
    <th>Name</th>
    <td><%= @teacher.name %></td>
  </tr>
  <tr>
    <th>Email Address</th>
    <td><%= @teacher.email_address %></td>
  </tr>
  <tr>
    <th>Date Of Birth</th>
    <td><%= @teacher.date_of_birth %></td>
  </tr>
</table>


<%= link_to 'Edit', edit_teacher_path(@teacher), class: 'btn btn-primary pull-right' %>

app/views/users/show.html.erb
<strong>Username</strong><%= @user.username %>
<strong>Email</strong><%= @user.email %>

app/views/welcome/index.html.erb
<h1>Hello Rails</h1>
<%= link_to 'Teacher', controller: 'teachers' %>
<%= link_to 'Idea', controller: 'ideas' %>